spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: customer-report-ingestion
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.folklabor.domain
      enable-auto-commit: false
    #        use.type.info.headers: false
    listener:
      ack-mode: manual_immediate
  #     properties:
  #       spring.json.add.type.headers: false
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: elasticsearch:9300
      repositories:
        enabled: true
      properties.client.transport.sniff: false
customer-report:
  customer-topic: com.folklabor.dist.customer.topic
server:
  port: 8080
